const language = {
  en: {
    about: `About me`,
    languages: `Languages`,
    skills: `Skills`,
    projects: `Projects`,
    education: `Education`,
    contacts: `Contacts`,
    cv_title: `CV`,
    education_title: `my EDUCATION`,
    first_speciality: `Thermal Power Engineer`,
    first_year: `SEP 2012 - JUN 2017`,
    first_university: `Belarusian national technical university`,
    second_speciality: `Frontend Developer`,
    second_year: `DEC 2021 - SEP 2022 `,
    second_university: `The Rolling Scopes School`,
    certificate_title: `my CERTIFICATE`,
    about_title: `about ME`,
    name: `ARTSIOM MIKULA`,
    job: `Junior Frontend Developer`,
    location: `Minsk, Belarus`,
    languages_title: `my LANGUAGES`,
    first_language: `Russian - Native`,
    second_language: `English - A2`,
    third_language: `Polish -  B2`,
    skills_title: `my SKILLS`,
    projects_title: `my PROJECTS`,
    contacts_title: `Find me in:`,
  },
  ru: {
    about: `Обо мне`,
    languages: `Языки`,
    skills: `Навыки`,
    projects: `Проекты`,
    education: `Образование`,
    contacts: `Контакты`,
    cv_title: `РЕЗЮМЕ`,
    education_title: `ОБРАЗОВАНИЕ`,
    first_speciality: `Инженер-теплоэнергетик`,
    first_year: `СЕН 2012 - ИЮНЬ 2017`,
    first_university: `Белорусский национальный технический университет`,
    second_speciality: `Фронтенд-разработчик`,
    second_year: `ДЕК 2021 - СЕН 2022 `,
    second_university: `The Rolling Scopes School`,
    certificate_title: `СЕРТИФИКАТЫ`,
    about_title: `обо МНЕ`,
    name: `АРТЁМ МИКУЛА`,
    job: `Младший фронтенд-разработчик`,
    location: `Минск, Беларусь`,
    languages_title: `ЯЗЫКИ`,
    first_language: `Русский - Носитель`,
    second_language: `Английский - Элементарный`,
    third_language: `Польский - Средний`,
    skills_title: `НАВЫКИ`,
    projects_title: `ПРОЕКТЫ`,
    contacts_title: `Найди меня в:`,
  },
};

export default language;
